# Generated by Django 4.0.2 on 2022-05-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0014_alter_comment_date_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='DURATION',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Длительность звонка'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='STATUS',
            field=models.CharField(choices=[('0', '-'), ('1', '-'), ('2', 'Ожидается'), ('3', 'Завершено'), ('4', 'Завершено автоматически')], max_length=1, verbose_name='Статус дела'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='TYPE_ID',
            field=models.CharField(choices=[('1', 'Встреча'), ('2', 'Звонок'), ('3', 'Задача'), ('4', 'Письмо')], db_index=True, max_length=1, verbose_name='Тип дела (встреча/звонрок/...)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='CALL_ID',
            field=models.CharField(db_index=True, max_length=75, unique=True, verbose_name='ID звонка в BX24'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='CALL_START_DATE',
            field=models.DateTimeField(verbose_name='Дата начала звонка'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='PHONE_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
