# Generated by Django 4.0.2 on 2022-05-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0015_activity_duration_alter_activity_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='DURATION',
        ),
    ]
