# Generated by Django 4.0.2 on 2022-05-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0016_remove_activity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ALLOWED_STATUS_DAY',
            field=models.BooleanField(default=False, verbose_name='Доступ к изменению статуса дня'),
        ),
        migrations.AddField(
            model_name='user',
            name='ALLOWED_VERIFICATION_MSG',
            field=models.BooleanField(default=False, verbose_name='Доступ к верификации сообщений'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='OWNER_NAME',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Название сущности к которой привязан звонок'),
        ),
    ]
